name: GodYouSuck
favicon: null
layout_spectrum: 0.3984418301843107
typography_spectrum: 0.6992754775565118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7717850613407791
  lightness: 0.826605022419244
  saturation: 0.6609212006442249
  rhythmicContrast: 0.20683185942471027
purpose: []
